n1=(input("Digite o nome da primeira pessoa:"))
id1=(input("Digite a idade da primeira pessoa:"))
n2=(input("Digite o nome da segunda pessoa:"))
id2=(input("Digite a idade da segunda pessoa:"))
n3=(input("Digite o nome da terceira pessoa:"))
id3=(input("Digite a idade da terceira pessoa:"))

ln=(n1, n2, n3)
li=(id1, id2, id3)
print("-")
print("-")
print("DADOS OBTIDOS DA PRIMEIRA PESSOA")
print("Nome:{}----Idade:{} anos".format(ln[0], li[0]))
print("-")
print("-")
print("DADOS OBTIDOS DA SEGUNDA PESSOA")
print("Nome:{}----Idade:{} anos".format(ln[1], li[1]))
print("-")
print("-")
print("DADOS OBTIDOS DA TERCEIRA PESSOA")
print("Nome:{}----Idade:{} anos".format(ln[2], li[2]))
