frase=input("Digite uma frase:")
print("Tamanho da frase:", len(frase))
metade=int(len(frase)/2)
pm=(frase[0:metade])
sm=(frase[metade:len(frase)])
print("-")
print("-")
print("Se a entrada for:", frase)
print("-")
print("-")
print("Saída:")
print("Primeira metade:",pm)
print("Segunda metade:",sm)
